name: Radar Email

on:
  workflow_dispatch:

jobs:
  enviar-radar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar libs
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy

      - name: Verificar arquivos
        run: |
          pwd
          ls -la
          echo "==== INICIO MAIN.PY ===="
          head -20 main.py
          echo "==== FIM MAIN.PY ===="

      - name: Rodar script
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          SENHA_APP: ${{ secrets.SENHA_APP }}
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
        run: |
          echo "Executando Python..."
          python main.py
